package com.company;

import java.util.Random;
import java.util.Scanner;

/*
It has three possible outcomes: a draw, a win or a loss. A player who decides to play rock will beat another player who
has chosen scissors ("rock crushes scissors" or "breaks scissors" or sometimes "blunts scissors"), but will lose to one
who has played paper ("paper covers rock"); a play of paper will lose to a play of scissors ("scissors cuts paper").
If both players choose the same shape, the game is tied and is usually replayed to break the tie.
 */
public class RockPaperScissor {
    public static void main(String[] args) {
        // 0 for Rock
        // 1 for Paper
        // 2 for Scissor

        Scanner sc = new Scanner(System.in);
        // Take input from User
        System.out.println("Enter 0 for Rock, 1 for Paper, 2 for Scissor");
        int userInput = sc.nextInt();

        // Generate a Random number
        Random random = new Random();
        int computerInput = random.nextInt(3);

        // Check conditions
        if(userInput == computerInput){
            System.out.println("Draw");
        }
        else if(userInput==0 && computerInput==2 || userInput==1 && computerInput==0 || userInput==2 && computerInput==1){
            System.out.println("You Win!");
        }
        else{
            System.out.println("Computer Win!");
        }

        // Random number generated by Computer
        //2System.out.println("Computer choice: "+ computerInput);
        if(computerInput==0){
            System.out.println("Computer choice: Rock");
        }
        else if(computerInput==1){
            System.out.println("Computer choice: Paper");
        }
        else if(computerInput==2){
            System.out.println("Computer choice: Scissor");
        }
    }
}
